- homebrew:
    name: kubectl
    state: present

- name: Install heptio authenticator
  get_url:
    url: https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-06-05/bin/darwin/amd64/heptio-authenticator-aws
    dest: '{{ ansible_env.HOME + "/bin" }}'
    mode: u+rwx
    force: no
