- homebrew:
    name: docker-machine-driver-xhyve
    state: present

- name: Fix docker-machine-driver-xhyve ownership
  shell: chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
  become: true

- name: Fix access permissions docker-machine-driver-xhyve
  shell: chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
  become: true

- homebrew_cask:
    name: minishift
    state: present
