- homebrew_cask:
    name: iterm2
    state: present

- name: Create iTerm in dock
  shell: dockutil --find 'iTerm' || dockutil --add '/Applications/iTerm.app'

- homebrew:
    name: zsh
    state: present

- homebrew:
    name: zsh-completions
    state: present

- name: Install oh-my-zsh
  shell: curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
