- name: "Finder: Enables ethernet for AirDrop"
  command: defaults write com.apple.NetworkBrowser BrowseAllInterfaces 1
- name: "Finder: show all filename extensions"
  command: defaults write NSGlobalDomain AppleShowAllExtensions -bool true
- name: "Finder: When performing a search, search the current folder by default"
  command: defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
- name: "Finder: Avoid creating .DS_Store files on network volumes"
  command: defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
- name: "Show the ~/Library folder"
  command: chflags nohidden ~/Library
- name: "Don't Ask confirmation for change extension"
  command: defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# copy wallpaper file to -> ~/.wallpapers/
# osascript -e 'tell application "Finder" to set desktop picture to POSIX file "~/.wallpapers/roppet.png"'
