---
- name: Set whether the Dock automatically hides
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true

- name: Remove all crap from Dock
  shell: dockutil --remove '{{ item }}'
  ignore_errors: true
  with_items: dockitems_to_remove

- name: Create items in dock
  shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'
  with_items: "{{ dockitems_to_persist }}"

- name: Create folders at the right side of the dock
  shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}' --section others
  with_items: "{{ dockfolders_to_persist }}"

- name: Fix order
  shell: dockutil --move '{{ item.name }}' --position {{ item.pos }}
  with_items: "{{ dockitems_to_persist }}"
