- include_role:
    name: app-sdkman

#- name: Check if caskroom/versions is installed
#  homebrew_tap: tap=caskroom/versions state=present

- include_role:
    name: app-jdk

- name: Install jEnv
  homebrew:
    name: jenv
    state: present

- name: Make jEnv scan all installed JDKs
  shell: eval 'mkdir -p ~/.jenv/versions; for d in /Library/Java/JavaVirtualMachines/jdk*/Contents/Home; do jenv add $d; done'
  args:
    creates: '{{ ansible_env.HOME + "/.jenv" }}'

- name: Scan all JDK executables
  command: jenv rehash

- include_role:
    name: app-maven

- include_role:
    name: app-intellij-ce
