- include_role:
    name: app-sdkman

- name: Install Java 8
  homebrew_cask:
    name: java8
    state: present

- name: Install Java 9
  homebrew_cask:
    name: java9
    state: present

- name: Install Latest Java
  homebrew_cask:
    name: java
    state: present

- name: Install jEnv
  homebrew:
    name: jenv
    state: present

- name: Make jEnv scan all installed JDKs
  shell: eval 'mkdir -p ~/.jenv/versions; for d in /Library/Java/JavaVirtualMachines/jdk*/Contents/Home; do jenv add $d; done'
  args:
    creates: '{{ ansible_env.HOME + "/.jenv" }}'

- name: Scan all JDK executables
  command: jenv rehash

- include_role:
    name: app-maven

- include_role:
    name: app-intellij-ce
